# Site settings
title: Antonio's picture
description: A photo album about <a href="https://antoniotrento.net">Antonio Trento</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://piccolio.github.io" # the base hostname & protocol for your site
author:

plugins:
  - jekyll-seo-tag
  

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url: https://facebook.com/lantoniotrento
github_url:
gitlab_url:
googleplus_url: https://plus.google.com/u/0/b/114870349902392641766/105909498949786982602
instagram_url: https://instagram.com/lantoniotrento
linkedin_url: https://linkedin.com/in/antoniotrento
pinterest_url: https://pinterest.com/antoniotrento
slack_url:
twitter_url: https://twitter.com/lantoniotrento

# Build settings
markdown: kramdown


# data for jekyll-seo-tags plugins
social:
  name: lantoniotrento
  links:
    - https://twitter.com/lantoniotrento
    - https://www.facebook.com/lantoniotrento
    - https://www.linkedin.com/in/antoniotrento
    - https://plus.google.com/u/0/b/114870349902392641766/105909498949786982602
    - https://github.com/jorigamy/jorigamy.github.io
    - https://keybase.io/antoniotrento
twitter:
  username: lantoniotrento

facebook:
 app_id:  #the app id from https://developers.facebook.com/
 admins:  #the page ID from https://www.facebook.com/pg/lantoniotrento (page-link), left click about scroll down and find 'Page ID'
 publisher:  #the page ID from https://www.facebook.com/pg/lantoniotrento (page-link), left click about scroll down and find 'Page ID'
