# Site settings
title: Antonio's picture
description: A photo album about <a href="https://lantoniotrento.github.io">Antonio Trento</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://piccolio.github.io" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url: https://facebook.com/lantoniotrento
github_url: https://github.com/antoniotrento
gitlab_url:
googleplus_url: https://plus.google.com/u/0/b/114870349902392641766/105909498949786982602
instagram_url: https://instagram.com/lantoniotrento
linkedin_url:
pinterest_url: https://pinterest.com/antoniotrento
slack_url:
twitter_url: https://twitter.com/lantoniotrento

# Build settings
markdown: kramdown
